.\"                                      Hey, EMACS: -*- nroff -*-
.de Vb \" Begin verbatim text
.ft CW
.nf
.ne \\$1
..
.de Ve \" End verbatim text
.ft R
.fi
..
.TH TIPGODOC 1 "2015-07-24"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
tipgodoc \- serving HEAD godoc from git
.SH SYNOPSIS
.B tipgodoc
.SH DESCRIPTION
Command tipgodoc is the beginning of the new tip.golang.org server, serving the latest HEAD straight from the Git oven.

Run tipgodoc \-help for more details.

.SH AUTHOR
.PP
This manual page was written by Michael Stapelberg <stapelberg@debian.org>,
for the Debian project (and may be used by others).
